# Generated by Django 5.0.6 on 2026-05-24 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REQUEST_CREATED", "Request Created"),
                            ("REQUEST_STATUS_CHANGED", "Request Status Changed"),
                            ("TASK_ASSIGNED", "Task Assigned"),
                            ("TASK_COMPLETED", "Task Completed"),
                            ("PROGRESS_UPDATED", "Progress Updated"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("DELIVERABLE_UPLOADED", "Deliverable Uploaded"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=50,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                ("object_type", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
